import dotenv from "dotenv";
dotenv.config();

export const env = {
  API_KEY_FIREBASE: process.env.API_KEY_FIREBASE,
  AUTH_DOMAIN_FIREBASE: process.env.AUTH_DOMAIN_FIREBASE,
  PROJECT_ID_FIREBASE: process.env.PROJECT_ID_FIREBASE,
  STORAGE_BUCKET_FIREBASE: process.env.STORAGE_BUCKET_FIREBASE,
  MESSAGING_SENDER_ID_FIREBASE: process.env.MESSAGING_SENDER_ID_FIREBASE,
  appId: process.env.APP_ID_FIREBASE,
  TOKEN_TELEGRAM: process.env.TOKEN_TELEGRAM,
  CHAT_ID_TELEGRAM: process.env.CHAT_ID_TELEGRAM,
};
